
##################################################################################
#                     				LOG SETTING 
##################################################################################

logging.level.org.springframework.web=ERROR
logging.level.nirmalya.aatithya.webmodule=DEBUG

#logging.file=F:\\Nirmalya Remote\\nERP\\logging\\webLogging.log\\
logging.file=/logging/webApplication.log
logging.file.max-size=10MB
 

##################################################################################
#									APPLICATION SETTING
##################################################################################
########### Local / demo / Production#############
server.port=2722

 
server.servlet.context-path=/
#spring.session.timeout.seconds=108000
server.servlet.session.timeout=120m
server.servlet.session.cookie.http-only=true 
server.servlet.session.tracking-modes=cookie
server.servlet.session.persistent=false
#################################################################################
#									Base URL
###############################################################################
###########   Local #############
#service.url.baseURL = http://localhost:2722/
#service.url.base= http://localhost:2722/

###########   Production #############
service.url.baseURL=https://admin-ducisgroup.nerp.in/
service.url.base=https://admin-ducisgroup.nerp.in/

############# rest url Local ############# 
service.url.defaultBaseURL=http://localhost:2721/nirmalyaRest

############# rest url production Server #############
#service.url.defaultBaseURL=http://api-ducisgroup.nerp.in/nirmalyaRest

service.url.user=${service.url.defaultBaseURL}/user/
service.url.restaurant=${service.url.defaultBaseURL}/restaurant/
service.url.property=${service.url.defaultBaseURL}/property/
service.url.maintenance=${service.url.defaultBaseURL}/maintenance/
service.url.inventory=${service.url.defaultBaseURL}/inventory/
service.url.laundry=${service.url.defaultBaseURL}/laundry/
service.url.housekeeping=${service.url.defaultBaseURL}/housekeeping/
service.url.frontdesk=${service.url.defaultBaseURL}/frontdesk/
service.url.master=${service.url.defaultBaseURL}/master/
service.url.gym=${service.url.defaultBaseURL}/gym/
service.url.gatepass=${service.url.defaultBaseURL}/gatepass/
service.url.roomservice=${service.url.defaultBaseURL}/roomservice/
service.url.kitchen=${service.url.defaultBaseURL}/kitchen/
service.url.otherservices=${service.url.defaultBaseURL}/otherservices/
service.url.member=${service.url.defaultBaseURL}/member/
service.url.beautyparlour=${service.url.defaultBaseURL}/beautyparlour/
service.url.spa=${service.url.defaultBaseURL}/spa/
service.url.parking=${service.url.defaultBaseURL}/parking/
service.url.saloon=${service.url.defaultBaseURL}/saloon/
service.url.sales=${service.url.defaultBaseURL}/sales/
service.url.account=${service.url.defaultBaseURL}/account/
service.url.hrms=${service.url.defaultBaseURL}/hrms/
service.url.employee=${service.url.defaultBaseURL}/employee/
service.url.reimbursement=${service.url.defaultBaseURL}/reimbursement/
service.url.leave=${service.url.defaultBaseURL}/leave/
service.url.attendance=${service.url.defaultBaseURL}/attendance/
service.url.nightclub=${service.url.defaultBaseURL}/nightclub/
service.url.document=${service.url.defaultBaseURL}/document/
service.url.asset=${service.url.defaultBaseURL}/asset/
service.url.qualitycontrol=${service.url.defaultBaseURL}/qualitycontrol/
service.url.production=${service.url.defaultBaseURL}/production/
service.url.planning=${service.url.defaultBaseURL}/planning/
service.url.recruitment=${service.url.defaultBaseURL}/recruitment/
service.url.projects=${service.url.defaultBaseURL}/projects/
service.url.customer=${service.url.defaultBaseURL}/customer/
service.url.ticket=${service.url.defaultBaseURL}/ticket/
service.url.notice=${service.url.defaultBaseURL}/notice/
service.url.pipeline=${service.url.defaultBaseURL}/pipeline/
service.url.hospitality=${service.url.defaultBaseURL}/hospitality/
service.url.audit=${service.url.defaultBaseURL}/audit/
service.url.api=${service.url.defaultBaseURL}/api/
service.url.mould=${service.url.defaultBaseURL}/mould/
service.url.purchase=${service.url.defaultBaseURL}/purchase/
service.url.trainingUrl=${service.url.defaultBaseURL}/training/
service.url.bidding=${service.url.defaultBaseURL}/bidding/
service.url.trial=${service.url.defaultBaseURL}/trial/
service.url.qa=${service.url.defaultBaseURL}/qa/
service.url.weight=${service.url.defaultBaseURL}/weight/
service.url.budget=${service.url.defaultBaseURL}/budget/
service.url.gst=${service.url.defaultBaseURL}/gst/
service.url.grc=${service.url.defaultBaseURL}/grc/
service.url.communication=${service.url.defaultBaseURL}/communication/
service.url.his=${service.url.defaultBaseURL}/his/
service.url.pharmacy=${service.url.defaultBaseURL}/pharmacy/
service.url.meeting=${service.url.defaultBaseURL}/meeting/
service.url.ticket-system=${service.url.defaultBaseURL}/ticket-system/
service.url.canteen=${service.url.defaultBaseURL}/canteen/
service.url.edms=${service.url.defaultBaseURL}/edms/
service.url.apprasial=${service.url.defaultBaseURL}/appraisal/
service.url.patient =${service.url.defaultBaseURL}/patient/
service.url.hotel =${service.url.defaultBaseURL}/hotel/

#################SERVER############################
service.url.fileUpload-laundry = /home/nerpin/nerp/fileupload/laundry/
service.url.fileUpload-restaurant = /home/nerpin/nerp/fileupload/restaurant/
service.url.fileUpload-hotel = /home/nerpin/nerp/fileupload/hotel/
service.url.fileUpload-sales = /home/nerpin/nerp/fileupload/sales/
service.url.fileUpload-inventory = /home/nerpin/nerp/fileupload/inventory/
service.url.fileUpload-beautyparlour =/home/nerpin/nerp/fileupload/beautyparlour/
service.url.fileUpload-reimbursement = /home/nerpin/nerp/fileupload/reimbursement/
service.url.fileUpload-store = /home/nerpin/nerp/fileupload/store/
service.url.challan =/home/nerpin/nerp/fileupload/challan/
service.url.gatePass = /home/nerpin/nerp/fileupload/gatePass/
service.url.fileUpload-uploadItem =/home/nerpin/nerp/fileupload/item/
service.url.barcodes =/home/nerpin/nerp/fileupload/barcodes/
service.url.fileUpload-procurement =/home/nerpin/nerp/fileupload/procurement/
service.url.fileUpload-trial = /home/nerpin/nerp/fileupload/document/
service.url.fileUpload-uploadAudit =/home/nerpin/nerp/fileupload/audit/
service.url.meetingUrl = https://service-node.nerp.in/api/v1/meetings/rohandarkbull@gmail.com

#################################################################################
#									File Upload Path
###############################################################################

###########   Local #############

#service.url.fileUpload-procurement = F:\\Nirmalya Remote\\APIL_nERP\\fileupload\\document\\
#service.url.fileUpload-uploadEmployee = D:\\Healthcare_nerp2.0\\fileupload\\
#service.url.fileUpload-organisation =F:\\Nirmalya Remote\\APIL_nERP\\fileupload\\document\\
#service.url.fileUpload-document = E:\\Nirmalya\\LMS\\fileupload\\document\\
#service.url.fileUpload-master = F:\\Nirmalya Remote\\APIL_nERP\\fileupload\\document\\
#service.url.fileUpload-taskdocument=F:\\Nirmalya Remote\\APIL_nERP\\fileupload\\taskdocument\\
#service.url.uploadImageCrm =F:\\Nirmalya Remote\\APIL_nERP\\fileupload\\crm\\
#service.url.fileUpload-property=F:\\Nirmalya Remote\\APIL_nERP\\fileupload\\property\\
#service.url.fileUpload-ticket=F:\\Nirmalya Remote\\APIL_nERP\\fileupload\\ticket\\
#service.url.userQrCode=F:\\Nirmalya Remote\\APIL_nERP\\fileupload\\userQrCode\\
#service.url.fileUpload-training=F:\\Nirmalya Remote\\APIL_nERP\\fileupload\\training\\
#service.url.staffQrCode=F:\\Nirmalya Remote\\APIL_nERP\\fileupload\\staffQrCode\\
#service.url.assetDocUrl=F:\\Nirmalya Remote\\APIL_nERP\\fileupload\\asset\\
#service.url.accountDocUpload=F:\\Nirmalya Remote\\APIL_nERP\\fileupload\\account\\
#service.url.fileUpload-communication=F:\\Nirmalya Remote\\APIL_nERP\\fileupload\\communication\\
#service.url.grcDocUrl=F:\\Nirmalya Remote\\APIL_nERP\\fileupload\\grc\\
#service.url.fileUpload-notice-policy=F:\\Nirmalya Remote\\APIL_nERP\\fileupload\\notice-policy\\
#service.url.fileUpload-resignation=F:\\Nirmalya Remote\\APIL_nERP\\fileupload\\resignation\\
#service.url.fileUpload-dms = D:\\htmlcheck\\
#service.url.fileUpload-omc = F:\\Nirmalya Remote\\APIL_nERP\\fileupload\\omc\\

#service.url.fileUpload-uploadEmployee = D:\\Healthcare_nerp2.0\\fileupload\\


###########  server #############
service.url.fileUpload-procurement = /data/fileupload/ducisgroup/document/
service.url.fileUpload-uploadEmployee = /data/fileupload/ducisgroup/employee/
service.url.fileUpload-organisation =/data/fileupload/ducisgroup/document/
service.url.fileUpload-document = /data/fileupload/ducisgroup/document/
service.url.fileUpload-master =/data/fileupload/ducisgroup/document/
service.url.fileUpload-taskdocument=/data/fileupload/ducisgroup/taskdocument/
service.url.uploadImageCrm=/data/fileupload/ducisgroup/crm/
service.url.fileUpload-property=/data/fileupload/ducisgroup/property/
service.url.fileUpload-ticket=/data/fileupload/ducisgroup/ticket/
service.url.userQrCode=/data/fileupload/ducisgroup/userQrCode/
service.url.fileUpload-training=/data/fileupload/ducisgroup/training/
service.url.staffQrCode=/data/fileupload/ducisgroup/staffQrCode/
service.url.assetDocUrl=/data/fileupload/ducisgroup/asset/
service.url.accountDocUpload=/data/fileupload/ducisgroup/account/
service.url.communicationDocUrl=/data/fileupload/ducisgroup/communication/
service.url.grcDocUrl=/data/fileupload/ducisgroup/grc/
service.url.fileUpload-notice-policy=/data/fileupload/ducisgroup/notice-policy/
service.url.fileUpload-resignation=/data/fileupload/ducisgroup/resignation/
service.url.fileUpload-dms=/data/fileupload/ducisgroup/dms/
service.url.fileUpload-omc=/data/fileupload/ducisgroup/vms/

 
################################################################################################
 
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=512MB
spring.servlet.multipart.max-request-size=512MB
spring.servlet.multipart.file-size-threshold=512MB
server.tomcat.max-http-post-size=-1

################################################################################################


########################################



###########   demo #############
#spring.mail.username=nirmalyalabs508@gmail.com
#spring.mail.password=jjffhicsosmtbild
############   Production ######
#spring.mail.username=info@apil.co.in
#spring.mail.password=nhelcytekizqfukc


# for jms configs 
ebug=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nirmalyalabs508@gmail.com
spring.mail.password=jjffhicsosmtbild
# Other properties
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# TLS , port 587
spring.mail.properties.mail.smtp.starttls.enable=true
